SELECT * FROM [dbo].[TABELA DE PRODUTOS];

DELETE FROM [dbo].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [SABOR] = 'Uva';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [SABOR] = 'Limão';

DELETE FROM [dbo].[TABELA DE PRODUTOS] WHERE [SABOR] = 'Limão';