SELECT * FROM [dbo].[TABELA DE PRODUTOS]

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] = 'PET';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 10;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] >= 4.555;

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] <'Lata';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] <> 'Lata';

SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 4.555;

SELECT * FROM [dbo].[TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSÃO] > 0.10;