SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO,  [LIMITE DE CREDITO] FROM [dbo].[TABELA DE CLIENTES]

-- SOMANDO O LIMITE DE CRÉDITO DE CADA ESTADO
SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- FAZENDO A MÉDIA DO LIMITE DE CRÉIDITOS DOS CLEINTES DE CADA ESTADO
SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- O MAIOR VALOR DO PREÇO DE LISTA POR EMBALAGEM
SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- O MENOR PREÇO DE LISTA POR EMBALAGEM
SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

--
SELECT [NOME DO PRODUTO], EMBALAGEM  FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM

-- CONTANDO A QUANTIDADE DE EMBALAGENS 
SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- SOMANDO O LIMITE DE CREDITO POR BAIRRO DO ESTADO DE SÃO PAULO
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO ORDER BY BAIRRO DESC

-- É OBRIGATÓRIO AGRUPAR TODOS OS CAMPOS STRINGS QUE APARECEM NO SELECT
SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] 
WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO, ESTADO

SELECT COUNT(*) 
FROM [dbo].[ITENS NOTAS FISCAIS] 
WHERE [CODIGO DO PRODUTO] = 1101035 AND [QUANTIDADE] = 99;
