/*DISTINCT SÓ VAI MOSTRAR AS LINHAS SEM A REPETIÇÃO*/

SELECT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Laranja'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]


SELECT DISTINCT [BAIRRO] FROM [dbo].[TABELA DE CLIENTES] WHERE CIDADE = 'Rio de Janeiro'