/*TOP 3 SÓ VAI MOSTRAR OS PRIMEIROS 3 NÚMEROS DAQUELA CONSULTA*/
/*O SELECT É RESOLVIDO, MAS SÓ É PEGADO OS 3 PRIMEIROS VALORES DA CONSULTA*/

SELECT * FROM [TABELA DE PRODUTOS]

SELECT TOP 3 * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT TOP 3 * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT TOP 3 EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT TOP 10 * FROM [dbo].[NOTAS FISCAIS] WHERE [DATA] = '2017/01/01'