

SELECT CEILING(12.333223) AS [ARREDONDAMENTO PRA CIMA]

SELECT FLOOR(12.333223) AS [ARREDONDAMENTO PRA BAIXO]

SELECT RAND()

SELECT ROUND(12.33323323, 2)

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),1) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS]

SELECT FLOOR(SUM(IMPOSTO*(QUANTIDADE*PREÇO))) AS [IMPOSTO PAGO] FROM [dbo].[NOTAS FISCAIS] NF
INNER JOIN [dbo].[ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) ='2016'  GROUP BY YEAR(DATA)

