UPDATE [dbo].[TABELA DE PRODUTOS] SET 
[EMBALAGEM] = 'Lata' ,
[PREÇO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931';

UPDATE [dbo].[TABELA DE PRODUTOS] SET 
[EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680';


UPDATE [dbo].[VENDEDORES] SET 
[NOME] = 'José Geraldo da Fonseca Junior'
WHERE [MATRICULA] = '00233';

