SELECT [CPF]
      ,[NOME]
      ,[ENDERECO 1]
      ,[ENDERECO 2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [SUCOES_VENDAS_01].[dbo].[TABELA DE CLIENTES]

  SELECT * FROM [SUCOES_VENDAS_01].[dbo].[TABELA DE CLIENTES];

  SELECT [CPF]
      ,[NOME]
  FROM [SUCOES_VENDAS_01].[dbo].[TABELA DE CLIENTES]

  
  SELECT [CPF] AS IDENTIFICADOR
      ,[NOME] AS CLIENTE
  FROM [SUCOES_VENDAS_01].[dbo].[TABELA DE CLIENTES]

  SELECT [NOME],
  [MATRICULA] 
  FROM [dbo].[TABELA DE VENDEDORES];