SELECT * FROM [dbo].[TABELA DE CLIENTES] ;

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11';

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11';

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11';

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995;

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 1;

SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 11;


SELECT * FROM [dbo].[TABELA DE VENDEDORES] WHERE YEAR([DATA ADMISSÃO]) >= 2016;

